# Exportable constants
# 22/04/2015
#' @export
estados.venezuela <- data.frame(
        shape.name <-c(
                "Distrito Federal",
                "Estado Amazonas",
                "Estado Anzoategui",
                "Estado Apure",
                "Estado Aragua",
                "Estado Barinas",
                "Estado Bolivar",
                "Estado Carabobo",
                "Estado Cojedes",
                "Estado Delta Amacuro",
                "Estado Falcon",
                "Estado Guarico",
                "Estado Lara",
                "Estado Merida",
                "Estado Miranda",
                "Estado Monagas",
                "Estado Nueva Esparta",
                "Estado Portuguesa",
                "Estado Sucre",
                "Estado Tachira",
                "Estado Trujillo",
                "Estado Vargas",
                "Estado Yaracuy",
                "Estado Zulia"),
        Name.UTF8 <-c(
                "Distrito Federal",
                "Estado Amazonas",
                "Estado Anzo\u00E1tegui",
                "Estado Apure",
                "Estado Aragua",
                "Estado Barinas",
                "Estado Bol\u00EDvar",
                "Estado Carabobo",
                "Estado Cojedes",
                "Estado Delta Amacuro",
                "Estado Falc\u00F3n",
                "Estado Gu\u00E1rico",
                "Estado Lara",
                "Estado M\u00E9rida",
                "Estado Miranda",
                "Estado Monagas",
                "Estado Nueva Esparta",
                "Estado Portuguesa",
                "Estado Sucre",
                "Estado Tachira",
                "Estado Trujillo",
                "Estado Vargas",
                "Estado Yaracuy",
                "Estado Zulia"),
        Name <-c(
                "Distrito Federal",
                "Estado Amazonas",
                "Estado Anzoategui",
                "Estado Apure",
                "Estado Aragua",
                "Estado Barinas",
                "Estado Bolivar",
                "Estado Carabobo",
                "Estado Cojedes",
                "Estado Delta Amacuro",
                "Estado Falcon",
                "Estado Guarico",
                "Estado Lara",
                "Estado Merida",
                "Estado Miranda",
                "Estado Monagas",
                "Estado Nueva Esparta",
                "Estado Portuguesa",
                "Estado Sucre",
                "Estado Tachira",
                "Estado Trujillo",
                "Estado Vargas",
                "Estado Yaracuy",
                "Estado Zulia"),
        Abb <- c(
                "DC",
                "AM",
                "AN",
                "AP",
                "AR",
                "BA",
                "BO",
                "CA",
                "CO",
                "DA",
                "FA",
                "GU",
                "LA",
                "ME",
                "MI",
                "MO",
                "NE",
                "PO",
                "SU",
                "TA",
                "TR",
                "VA",
                "YA",
                "ZU") )
colnames(estados.venezuela) <- c("shape.name", "Name.UTF8", "Name", "Abb")
rownames(estados.venezuela) <- estados.venezuela$Abb